name: Run tests on Linux

on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  # In master we want to run for every commit, in other branches — only for the last one
  group: ${{
    ( github.ref == 'refs/heads/master' &&
    format('{0}/{1}/{2}', github.workflow, github.ref, github.sha) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

env:
  NIX_CONFIG: access-tokens = github.com=${{ secrets.PRIVATE_REPO_GITHUB_TOKEN }}

jobs:
  build-and-test:
    name: Run tests workflow on Release build
    runs-on: [ self-hosted, Linux, X64, aws_autoscaling ]
    steps:
      # https://github.com/actions/checkout/issues/1552
      - name: Clean up after previous checkout
        run: chmod +w -R ${GITHUB_WORKSPACE}; rm -rf ${GITHUB_WORKSPACE}/*;

      - name: Checkout zkEVM-framework
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive --depth=1

      - name: Configure CMake
        #env:
        #  BOOST_ROOT: "${{ steps.install-boost.outputs.BOOST_ROOT }}"
        run: |
          cmake . \
            -G "Ninja" \
            -B build \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build assigner
        run: |
          cmake --build build

      - name: Run checks
        run: nix flake -L check
